import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        //最终返回语句
        String last="";
        //所有菜品
        List<Item>items=itemRepository.findAll();
        //所有折扣方式
        List<SalesPromotion>salesPromotions=salesPromotionRepository.findAll();
        //所有半价菜
        List<String>discountItems=salesPromotions.get(1).getRelatedItems();
        List<String>pay1Items=new ArrayList<String>();
        //是否使用优惠
        boolean flag=false;
        //pay1菜品半价，pay2满30-6，total不使用优惠
        int pay1=0,pay2=0,total=0;
        //记录半价菜的名称和价格
        Map <String,Double>discountMap=new HashMap();
        for (int i=0;i<discountItems.size();i++){
            for (int j=0;j<items.size();j++){
                if(items.get(j).getId().equals(discountItems.get(i))){
                    discountMap.put(items.get(j).getName(),items.get(j).getPrice()/2);
                }
            }
        }
        last+="============= 订餐明细 =============\n";
        //System.out.print( "============= 订餐明细 =============\n");
        for(int i = 0 ; i < inputs.size() ; i++) {
            String str=inputs.get(i);
            String itemID=str.substring(0, str.indexOf("x")).trim();
            String itemCount=str.substring(str.indexOf("x")+1).trim();
            //根据ID找到菜名和价格
            for (int j=0;j<items.size();j++){
                String tempId= items.get(j).getId();
                String tempName= items.get(j).getName();
                if(tempId.equals(itemID)){
                    Item temp=items.get(j);
                    int money=(int)Math.round(temp.getPrice())*Integer.parseInt(itemCount);
                    last+=temp.getName()+" x "+itemCount+" = "+money+"元\n";
                   // System.out.print(temp.getName()+" x "+itemCount+" = "+money+"元\n");
                    total+=money;
                    if (discountMap.containsKey(tempName)){
                        pay1+=discountMap.get(tempName)*Integer.parseInt(itemCount);
                        pay1Items.add(tempName);
                        flag=true;
                    }else{
                        pay1+=money;
                    }
                }
            }
        }
        //System.out.println(total+"   "+pay1);
        if (total>=30)
        {
            flag=true;
            pay2=total-6;
        }
        last+="-----------------------------------\n";
        //System.out.print( "-----------------------------------\n");
        if(flag==true){
            last+="使用优惠:\n";
            //System.out.print("使用优惠：\n");
            if(pay1<pay2){
                last+=salesPromotions.get(1).getDisplayName()+"(";
                //System.out.print(salesPromotions.get(1).getDisplayName()+"(");
                for(int i=0;i<pay1Items.size();i++){
                    if(i!=pay1Items.size()-1){
                        last+=pay1Items.get(i)+"，";
                       // System.out.print(pay1Items.get(i)+"，");
                    }
                    else{
                        last+=pay1Items.get(i);
                       // System.out.print(pay1Items.get(i));
                    }
                }
                last+=")，省"+(total-pay1)+"元\n-----------------------------------\n总计："+pay1+"元\n===================================";
               // System.out.print(")，省"+(total-pay1)+"元\n");
               // System.out.print("总计："+pay1+"元\n");
               // System.out.print("===================================");
            }else {
                last+=salesPromotions.get(0).getDisplayName()+"，省"+(total-pay2)+"元\n-----------------------------------\n总计："+pay2+"元\n===================================";
               // System.out.print(salesPromotions.get(0).getDisplayName()+"，省"+(total-pay2)+"元\n");
               // System.out.print("总计："+pay2+"元\n");
               // System.out.print("===================================");
            }
        }else {
            last+="总计："+total+"元\n===================================";
           // System.out.print("总计："+total+"元\n");
            //System.out.print("===================================");
        }

        System.out.println(last);

        return last;
    }
}
